# https://opengameart.org/content/icons-food

texture_width = 160
texture_height = 160

# [0] Banana
[[sprites]]
x = 0
y = 0
width = 32
height = 32

# [1] Cherry
[[sprites]]
x = 0
y = 32
width = 32
height = 32

# [2] Muffin
[[sprites]]
x = 0
y = 64
width = 32
height = 32

# [3] Burger
[[sprites]]
x = 0
y = 96
width = 32
height = 32

# [4] French fries
[[sprites]]
x = 0
y = 128
width = 32
height = 32

# [5] Orange
[[sprites]]
x = 32
y = 0
width = 32
height = 32

# [6] Donut
[[sprites]]
x = 32
y = 32
width = 32
height = 32

# [7] Bread
[[sprites]]
x = 32
y = 64
width = 32
height = 32

# [8] Deep fried butter
[[sprites]]
x = 32
y = 96
width = 32
height = 32

# [9] Fish
[[sprites]]
x = 32
y = 128
width = 32
height = 32

# [10] Apple
[[sprites]]
x = 64
y = 0
width = 32
height = 32

# [11] Ice cream
[[sprites]]
x = 64
y = 32
width = 32
height = 32

# [12] Coffee
[[sprites]]
x = 64
y = 64
width = 32
height = 32

# [13] Pizza
[[sprites]]
x = 64
y = 96
width = 32
height = 32

# [14] Avocado
[[sprites]]
x = 64
y = 128
width = 32
height = 32

# [15] Watermelon
[[sprites]]
x = 96
y = 0
width = 32
height = 32

# [16] Fried egg
[[sprites]]
x = 96
y = 32
width = 32
height = 32

# [17] Hotdog
[[sprites]]
x = 96
y = 64
width = 32
height = 32

# [18] Carrot
[[sprites]]
x = 96
y = 96
width = 32
height = 32

# [19] Lollipop
[[sprites]]
x = 96
y = 128
width = 32
height = 32

# [20] Pineapple
[[sprites]]
x = 128
y = 0
width = 32
height = 32

# [21] Cheese
[[sprites]]
x = 128
y = 32
width = 32
height = 32

# [22] Beer
[[sprites]]
x = 128
y = 64
width = 32
height = 32

# [23] Milk
[[sprites]]
x = 128
y = 96
width = 32
height = 32

# [24] Chocolate
[[sprites]]
x = 128
y = 128
width = 32
height = 32
