# https://assetstore.unity.com/packages/2d/environments/free-platform-game-assets-85838

texture_width = 200
texture_height = 103

[[sprites]]
x = 0
y = 0
width = 100
height = 103

[[sprites]]
x = 100
y = 0
width = 100
height = 103
