[aliens]
base_health = 100.0
count = 16
loot_pool = [
	{ probability = 0.24, count = [1, 1], item = "beer" },
	{ probability = 0.1, count = [1, 2], item = "bread" },
	{ probability = 0.1, count = [1, 1], item = "chocolate" },
	{ probability = 0.06, count = [1, 1], item = "fish" },
	{ probability = 0.16, count = [1, 4], item = "pizza" },
]
walking.acceleration = 20.0
walking.drag = 5.0

[player]
attack.cooldown = 0.8
attack.power = 34.0
attack.range = 2.0
walking.acceleration = 60.0
walking.drag = 5.0
